### ISSUE TITLE
Pdf Export Image Problem.

### ISSUE THREAD

**Issue by coderkan** [ardacetinkaya/json-as-cv#1]
Hi @ardacetinkaya ,

It's a good repo. Thanks for that. 
When I try to export cv, the pdf format of cv is not readable. It has blurry look.

I added sample screenshot below.

![image](https://user-images.githubusercontent.com/8382599/94348017-c56c1080-0041-11eb-85b0-7c63e82499ab.png)

Regards.
Erkan

**Comment by ardacetinkaya** [comment]
Thanks a lot. Please check #2 for better export feature.
